name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0

      # - name: Install dependencies
      #   run: wally install

      - name: Generate sourcemap.json
        run: rojo sourcemap -o sourcemap.json

      - name: Download global Roblox types
        run: curl -o scripts/roblox.d.lua https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua

      - name: Analyze
        run: luau-lsp analyze --settings=scripts/analyze-settings.json --defs=scripts/roblox.d.lua --base-luaurc=.luaurc --sourcemap=sourcemap.json --ignore="modules/**" src

      - name: Check code quality
        run: |
          selene src
          stylua --check src

      - name: Build model
        run: rojo build -o place.rbxl
